# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15lAruCfL1iWQpA0-yYuRUrggURIT-0RL
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

# Load an image using matplotlib
image = plt.imread('palm-trees.jpg')  # Use a local image path
if image.dtype == np.uint8:
    image = image / 255.0  # Normalize if needed

# Reshape the image to a 2D array of pixels (height*width, RGB)
pixels = image.reshape(-1, 3)

# Set the number of colors (clusters)
n_colors = 3

# Fit KMeans on the pixel data
kmeans = KMeans(n_clusters=n_colors, random_state=42, n_init=10)
kmeans.fit(pixels)

# Replace each pixel with the nearest cluster center
quantized_pixels = kmeans.cluster_centers_[kmeans.labels_]

# Reshape to original image shape
quantized_image = quantized_pixels.reshape(image.shape)

# Plot original and quantized images side by side
fig, ax = plt.subplots(1, 2, figsize=(12, 6))
ax[0].imshow(image)
ax[0].set_title("Original Image")
ax[0].axis('off')

ax[1].imshow(quantized_image)
ax[1].set_title(f"Quantized Image ({n_colors} colors)")
ax[1].axis('off')

plt.tight_layout()
plt.show()